### ISSUE TITLE
We need docs

### ISSUE THREAD

**Issue by jbusecke** [jbusecke/xmovie#13]
The explanations in the Readme are limited and do not explore all options already available. 
xmovie needs a proper documentation. This is probably the most pressing issue at the moment.

**Comment by saylimulay88** [comment]
I would like to work on enhancing the Readme.

**Comment by jbusecke** [comment]
Awesome! Do you have something particular in mind that can be improved? If that is the case I would be happy to review a pull request.

More generally I would like to use the readme as a short description with a minimal example and move more detailed descriptions of the options, presets etc into a separate documentation. I have a few more general design ideas that I would like to implement and then I would start describing the modular design and give detailed examples in the documentation. Any help for that would also be greatly appreciated.

**Comment by saylimulay88** [comment]
My priority would be to test the existing content and look for gaps as an end user. (I would need help with filling those gaps.) I like your idea of having separate detailed documentation with examples.

**Comment by jbusecke** [comment]
That sounds great! I recently pushed a commented notebook (First_steps.ipynb). I think it would be phenomenal if. you could try to test that and see if everything is explained in sufficient detail. If anything is unclear we can fix it and then port the content of the notebook to the docs once they are up and running.

Dont hesitate to ask any questions over here, things are not yet perfectly explained 😬.

Thanks for using xmovie!

**Comment by zmoon** [comment]
@jbusecke I think this issue could be closed

**Comment by jbusecke** [comment]
Yes closing now. Thanks again for all your work @zmoon
