### ISSUE TITLE
New framerate option not producing expected results

### ISSUE THREAD

**Issue by tomchor** [jbusecke/xmovie#16]
@jbusecke I have tested the framerate option but for reason it's not outputting the correct results for me. At least it's not the result I expected.

I'm trying to write a DataFrame with 42 frames here. However, if I set framerate=10, the number of frames of the video is only 18. If I set framerate=2, the number of frames of the video is only 5.

I'm pasting the relevant line of `MP4Box -info` below for both cases.

framerate=10:

`Media Info: Language "Undetermined (und)" - Type "vide:avc1" - 18 samples`

framerate=2

`Media Info: Language "Undetermined (und)" - Type "vide:avc1" - 5 samples`

The fps itself seems to be correctly set: 

`Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 3600x1600 [SAR 1:1 DAR 9:4], 139479 kb/s, 10 fps, 10 tbr, 10240 tbn, 20 tbc (default)` for fps=10.

`Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 3600x1600 [SAR 1:1 DAR 9:4], 36892 kb/s, 2 fps, 2 tbr, 16384 tbn, 4 tbc (default)` for fps=2.

This can probably be fixed by manually passing flags to `ffmpeg` (although I haven't tried), but I think it's better if this behavior is corrected, right? Am I missing something here or is it really not the expected behavior?

**Comment by jbusecke** [comment]
That is odd indeed. Could you try to execute the `First_Steps.ipynb` notebook and see if the problem persists with the `movie_slow.mp4` and 'movie_fast.mp4`, which are generated? For me these have the same date as the last frame (which I assume means that the total amount of frames is equal).

**Comment by tomchor** [comment]
@jbusecke I ran it and the issue persists. `movie_fast.mp4` has 122 frames, and `movie_slow.mp4` has 32. Same for the gifs. I inspected the creation of the `png`s and all the frames are created. So the bug happens when putting them together.

Here's a pastebin with some of the output: https://pastebin.com/HKMvBKKf
For some reason when I run this outside of a notebook I get an error and can't log the output. So I only have the limited amount of lines hte jupyter notebook allows me to get. I hope this helps figure it out.

Here's my ffmpeg version: `ffmpeg version N-81772-g99b823f`

I'll test this in some other computer to check as soon as I can.

**Comment by tomchor** [comment]
Okay, I ended up running it on my laptop just now. The problem apparently persists. Version is `ffmpeg version n4.1.3`.

A side note. Right now if I run a script again and I forget to delete the previous video, the package generates every single frame (which takes a while) and only then it throws an error and let's me know that I have to set `overwrite=True`. It woudl be much better if the package would first check that before generating every frame.

**Comment by jbusecke** [comment]
That is very odd. I will test this some more and figure out whats going on. One more question: Did you install ffmpeg using the conda test environment or externally?

Would you mind raising another issue for the overwrite issue? That I can fix rather quickly I think and that way we keep a clean record of this separate issue. Thanks

**Comment by tomchor** [comment]
It was installed externally, unless it was installed as a dependency of
another package and I haven't realized. Should I try installing it via
conda?

I'll open another issue when I get the chance for the overwrite thing!

**Comment by jbusecke** [comment]
If you could install the python 3.7 environment from https://github.com/jbusecke/xmovie/blob/master/ci/environment-py37.yml, and run it there,
that would help a lot in identifying the source of the error.

Cheers

Julius J.M. Busecke, PhD (he/him)
———————————————
Postdoctoral Research Associate
Princeton University • Geosciences
408A Guyot Hall • Princeton NJ
jbusecke.github.io

**Comment by tomchor** [comment]
Tested it using your pre-defined environment and the results were the same:

For the fast movie: `Media Info: Language "Undetermined (und)" - Type "vide:avc1" - 122 samples`

For the slow movie: `Media Info: Language "Undetermined (und)" - Type "vide:avc1" - 32 samples`

ffmpeg version: `ffmpeg version n4.1.3 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8.2.1 (GCC) 20181127`

And I'm using the conda-installed ffmpeg: 
```
xmovie$ which ffmpeg
/home/tomas/miniconda3/envs/test_env_xmovie/bin/ffmpeg
```

Not sure what's happening here. Are you sure that when you generate your movie in your computer all the frames are there? Btw, I'm counting with `MP4Box -info movie_fast.mp4`

I don't know a lot about ffmpeg, but have you taken a look at how `matplotlib` does it?

**Comment by jbusecke** [comment]
Ok, I dug a bit deeper into FFmpeg and seem to have found the culprit: Setting the framerate of the input (the frames) *and* output (movie) to the same value is required.

So now the total framerate (tested with opencv, see tests) will show the same total amount of frames for different framerates. I have implemented this in #19. 

Does this fix your issue as well?

**Comment by jbusecke** [comment]
I also wanted to mention that I have changed the constant bitrate to 15 for the default. This should probably be an option in the future aswell.

**Comment by tomchor** [comment]
I can confirm that I'm experiencing the correct behavior now. Thanks for fixing/implementing this!

**Comment by jbusecke** [comment]
Awesome. Thank YOU for pointing that out and testing on your side.
