### ISSUE TITLE
Overwriting error should come before generating the frames

### ISSUE THREAD

**Issue by tomchor** [jbusecke/xmovie#17]
Right now if I run a script again and I forget to delete the previous video, the package generates every single frame (which takes a while) and only then it throws an error and let's me know that I have to set `overwrite=True`. It would be much better if the package would first check that before generating every frame. That way if the error is to be raised, it will save me some minutes of dummy processing.

Thanks!

**Comment by jbusecke** [comment]
I moved the check to the `Movie.save` routine, which raises an error if either file (mp4/gif) exists.

**Comment by jbusecke** [comment]
Closed via #18
