### ISSUE TITLE
Using joblib to parallelize plotting

### ISSUE THREAD

**Issue by tomchor** [jbusecke/xmovie#34]
I realize there's another issue about the same functionality using dask, but apparently there are some glitches that haven't been easy to resolve. There were talks about dask's `map_blocks` but nothing got implemented. Today I came across an alternative by @ali-ramadhan, which is [joblib](https://joblib.readthedocs.io/en/latest/), which might be worth considering.

You can see it being used in [this script](https://github.com/CliMA/Oceananigans.jl/blob/master/validation/lid_driven_cavity/plot_lid_driven_cavity.py), and apparently the only "trick" needed here was to load the dataset in the function is that he "needed to open the dataset inside the function called by joblib". Other than that I think all that was needed was the addition of one joblib call in line 127: https://github.com/CliMA/Oceananigans.jl/blob/7a2c52442b780222e6700f5a99e3be24c4de909d/validation/lid_driven_cavity/plot_lid_driven_cavity.py#L127

CC: @dcherian @ali-ramadhan

**Comment by dcherian** [comment]
Sure this works well as long as you're plotting a variable saved on disk, or a derived quantity that doesn't depend on other files, and also not on a distributed cluster (maybe)?.

There's a thread on map_blocks here: https://discourse.pangeo.io/t/using-dask-to-parallelize-plotting/1179/10

**Comment by dcherian** [comment]
I;m sorry, my reply was rude.

This is a great approach if you can read your dataset from within the function. You could also use `dask.delayed` on that function and it would work well. The `map_blocks` approach is more general but also runs the risk of "standard" dask issues like really big graphs etc. Hopefully that makes clear what the tradeoffs are.

**Comment by tomchor** [comment]
Thanks, it does. Once I get more knowledge of dask I'll try to implement the ask approach.

Thanks

**Comment by ali-ramadhan** [comment]
I've had pretty good luck using joblib + matplotlib/Cartopy up to ~100 cores (haven't tried more) and the data I'm plotting definitely fits in memory (the dataset might not).

I guess I've always used it to make lots of _little_ plots, never having to make any _huge_ plots of data that doesn't fit in memory. This might be a pretty different problem to the Pangeo big data problem?

Would be interesting to try `dask.delayed`!

**Comment by jbusecke** [comment]
Hey folks, thanks for the suggestion. I in fact implemented `dask.delayed` in my initial approach [summarized here](https://github.com/jbusecke/xmovie/issues/6), and the speedup was very nice. I am very keen on the implementation in #35, since I think `map_blocks` seems like a great way to implement this in a general way. 
But I will definitely keep this in mind until we find a good solution to this important problem.

**Comment by jbusecke** [comment]
#35 is showing really good promise (and I think can be merged soon). Do folks here think we can close this issue in favor of #35 ?

**Comment by tomchor** [comment]
I started both this issue and PR #35, and I completely agree that this is about to be made obsolete! I started this before opening #35 just to discuss and see what the best way to implement was.

**Comment by jbusecke** [comment]
Awesome. Closing.
