### ISSUE TITLE
The scheduled build failed

### ISSUE THREAD

**Issue by jbusecke** [jbusecke/xmovie#41]
The scheduled [CI](https://github.com/xgcm/xgcm/actions) failed for python 3.9. Not sure if there is an issue with dependencies or just a glitch. 

I have restarted the jobs to exclude the latter for now. 

Once this is resolved, I will tag v0.2.0.

**Comment by tomchor** [comment]
Just an FYI, I have been using xmovie with py3.9 pretty much ever since it was released months ago and I haven't encountered any problems

**Comment by jbusecke** [comment]
Ok I think I have it sorted.

The badge should be fixed with #42, and I also took a minute to actually add python 3.8/3.9 to the CI (we did not test those before).

The problem over at [xgcm](https://github.com/xgcm/xgcm/actions) went away, so I assume this was just a glitch on either the github or conda side.

**Comment by jbusecke** [comment]
Closed via #43
