### ISSUE TITLE
Title on Rotating globe preset

### ISSUE THREAD

**Issue by kerhalkarsid** [jbusecke/xmovie#79]
Hello, I loved the xmovie module: it is very neat (especially the rotating globe preset). In the case of the rotating globe preset, is there a way to have the date on the top of the gif? Also the ability to customize the colorbars (or in general), making the plots more user-defined would be great for the visualization
![movie_rotating](https://user-images.githubusercontent.com/66088958/157457517-260f1ce9-0249-470d-82d6-2c001e617f93.gif)
.

**Comment by kerhalkarsid** [comment]
Thank you @jbusecke ! This was very useful. I am on my way to implement this in my codes: thanks again

**Comment by jbusecke** [comment]
If you can share the results, make sure to post them somewhere (twitter?). I love to see what people are doing with this package!

**Comment by kerhalkarsid** [comment]
I can share the results on twitter. Thanks
