### ISSUE TITLE
Wrong version appearing on v0.2.2 release

### ISSUE THREAD

**Issue by tomchor** [jbusecke/xmovie#81]
I see that this has been fixed on the main branch (I think), but the current tagged release (0.2.2) still has `__version__` == 0.1 due to this line: https://github.com/jbusecke/xmovie/blob/333d3012008178a42db35a4678dbb414adab2521/xmovie/__init__.py#L1

So when I import the package I get:

```python
In [1]: import xmovie

In [2]: xmovie.__version__
Out[2]: '0.1.0'
```

This isn't a major issue, but it took me 20 min of investigating to figure out what was going on! So I'd suggest tagging a new patch release right now to avoid confusion with other users.

Thanks!

**Comment by jbusecke** [comment]
Thanks for letting me know. Ill do that right away.

**Comment by jbusecke** [comment]
I actually bumped to 0.3.0 because we added some breaking changes https://github.com/jbusecke/xmovie/releases/tag/v0.3.0. 
Once this is done could you check this again? Thanks

**Comment by jbusecke** [comment]
https://github.com/conda-forge/xmovie-feedstock/pull/2

**Comment by tomchor** [comment]
Just installed it and can confirm it now shows the expected output:

```python
In [1]: import xmovie

In [2]: xmovie.__version__
Out[2]: '0.3.0'
```

Thanks!

**Comment by jbusecke** [comment]
Awesome, thanks for pointing this out!
