### ISSUE TITLE
Parallel plotting isn't working with Datasets

### ISSUE THREAD

**Issue by tomchor** [jbusecke/xmovie#82]
Parallel plotting seems to be working fine when the input is a DataArray, but I keep getting an error when trying to plot a Dataset. Consider the example below (adapted from the docs):

```python
import xarray as xr
from xmovie import Movie

ds = xr.tutorial.open_dataset('air_temperature').isel(time=slice(0, 50))

def custom_plotfunc(ds, fig, tt, *args, **kwargs):
    station = dict(x=100, y=150)
    ds_station = ds.sel(**station).air
    (ax1, ax2) = fig.subplots(ncols=2)
    ds.isel(time=tt).plot(ax=ax1, vmin=ds.min(), vmax=ds.max(), cmap='RdBu_r')
    ds_station.isel(time=slice(0,tt+1)).plot.line(ax=ax2, x='time')
    return None, None

mov_parallel = Movie(ds.chunk({'time':1}), vmin=230, vmax=310, input_check=False)
mov_parallel.save(
    'movie_parallel.mov',
    parallel=True,
    overwrite_existing=True,
)
```

This fails with

```python
In [1]: %run mwe.py
/home/tomas/miniconda3/envs/p39/lib/python3.9/site-packages/xmovie/presets.py:18: UserWarning: No `fieldname` supplied. Defaults to `air`
  warnings.warn(
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~/repos/Oceananigans.jl/sandbox/mwe.py:15, in <module>
     12     return None, None
     14 mov_parallel = Movie(ds.chunk({'time':1}), vmin=230, vmax=310, input_check=False)
---> 15 mov_parallel.save(
     16     'movie_parallel.mov',
     17     parallel=True,
     18     overwrite_existing=True,
     19 )
     21 pause
     23 mov_parallel = Movie(ds.air.chunk({'time':1}), vmin=230, vmax=310)

File ~/miniconda3/envs/p39/lib/python3.9/site-packages/xmovie/core.py:517, in Movie.save(self, filename, remove_frames, remove_movie, progress, verbose, overwrite_existing, parallel, parallel_compute_kwargs, framerate, ffmpeg_options, gif_palette, gif_resolution_factor, gif_framerate)
    515 # print frames
    516 if parallel:
--> 517     self.save_frames_parallel(
    518         dirname, parallel_compute_kwargs=parallel_compute_kwargs
    519     )
    520 else:
    521     self.save_frames_serial(dirname, progress=progress)

File ~/miniconda3/envs/p39/lib/python3.9/site-packages/xmovie/core.py:393, in Movie.save_frames_parallel(self, odir, parallel_compute_kwargs)
    389 if da.chunks is None:
    390     raise ValueError(
    391         f"Input data needs to be a dask array to save in parallel. Please chunk the input with single chunks along {framedim}."
    392     )
--> 393 framedim_chunks = da.chunks[da.dims.index(framedim)]
    395 if not all([chunk == 1 for chunk in framedim_chunks]):
    396     raise ValueError(
    397         f"Input data needs to be a with single chunks along {framedim}. Got these chunks instead ({framedim_chunks})"
    398     )

AttributeError: 'Frozen' object has no attribute 'index'
```

I'm sure this is something simple to solve due to some change in `dask`'s API or something, but since I don't have time to investigate it and solve it right now I figured I'd at least report it.

CC @wenegrat: you mentioned a couple of weeks ago that the parallel feature wasn't working for you and I'm pretty sure this is why!

**Comment by tomchor** [comment]
> Actually this is bit of bad coding on my end. Currently the code does not allow datasets I believe. A really hacky way to get a dataset into the function is just to provide it as an additional argument (ugly I know, but it has worked for me in the past).

If I'm not using the parallel feature I don't get any problems using datasets. The only thing I need is to pass the `input_check=False` kwarg.



> But looking at your code, I wonder why you are even passing a dataset? I belive this line
> 
> ```python
> ds.isel(time=tt).plot(...)
> ```
> 
> would not work either way with xarray?

This is just an example, but I do actually need to use datasets (I'd say that 85% of the times I need datasets). In previous versions this definitely was working (I know because I have an environment with an older version of xmovie/xarray/dask that I frequently use to plot datasets in parallel) so this is a newly introduced bug (either by xmovie or xarray or dask).



> Overall this point is coming up repeatedly, and it should be properly fixed. I suspect this will require some careful refactoring/documentation.

By this point do you mean the lack of support for datasets? If so, like I said, it's never been an issue for me (until now with the parallel flag).

> This package has fallen off my priority list for a while now, but I think in the near future I could make some time. It would be great to have some more eyes on it though. Do you think you have some cycles available to work on this?

Unfortunately I'm pretty busy over the next weeks. I can probably make some time to fix this bug specifically, but not enough to do any major/medium code refactoring...

**Comment by jbusecke** [comment]
Oh thanks for the clarification. Its not that datasets are not working, but the support is not really explicit (see e.g. the `input_check=False` 'trick'), specifically they are not tested!

Ill try to put some time together for some work on this package I think, and will keep this in mind for sure.
