### ISSUE TITLE
Error saving when using parallel option on Dataset, index error on the dims

### ISSUE THREAD

**Issue by scollis** [jbusecke/xmovie#88]
install method: pip
OS: Linux
Version: 0.1.0
I have a 1,000 frame dataset (yes I realize full support is yet to be added). I am trying to use the parallel option.
![Screen Shot 2022-03-23 at 6 48 32 AM](https://user-images.githubusercontent.com/825351/159695086-3e17e5ed-6f56-41c2-afe5-d164f14e1f26.png)

```
def custom_plotfunc(ds, fig, tt, *args, **kwargs):
    ax = plt.axes(projection=projection)
    ds_lat_lon.reflectivity.sel(z=1000, method="nearest").isel(time=tt).plot.pcolormesh(vmin=-10, vmax=64,
                                              cmap=pyart.graph.cm_colorblind.HomeyerRainbow)
    gl = ax.gridlines(draw_labels=True,
                  linewidth=2, color='gray', alpha=0.5, linestyle='--')
    ax.add_feature(cfeature.COASTLINE)
    
    return None, None
```

```mov_parallel = Movie(ds_lat_lon.chunk({'time':1}), custom_plotfunc, input_check=False)```

```mov_parallel.save(
    'movie_parallel.gif',
    parallel=True,
    overwrite_existing=True,
    gif_resolution_factor=1.0
)```

Error
```---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-88-2597ccea2720> in <module>
      2     'movie_parallel.gif',
      3     parallel=True,
----> 4     overwrite_existing=True,
      5 )

~/.conda/envs/pyart-simple/lib/python3.6/site-packages/xmovie/core.py in save(self, filename, remove_frames, remove_movie, progress, verbose, overwrite_existing, parallel, parallel_compute_kwargs, framerate, ffmpeg_options, gif_palette, gif_resolution_factor, gif_framerate)
    516         if parallel:
    517             self.save_frames_parallel(
--> 518                 dirname, parallel_compute_kwargs=parallel_compute_kwargs
    519             )
    520         else:

~/.conda/envs/pyart-simple/lib/python3.6/site-packages/xmovie/core.py in save_frames_parallel(self, odir, parallel_compute_kwargs)
    391                 f"Input data needs to be a dask array to save in parallel. Please chunk the input with single chunks along {framedim}."
    392             )
--> 393         framedim_chunks = da.chunks[da.dims.index(framedim)]
    394 
    395         if not all([chunk == 1 for chunk in framedim_chunks]):

AttributeError: 'Frozen' object has no attribute 'index'```

Just to check its not my custom func
```
ds_lat_lon.chunk({'time':1}).dims.index

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-94-4306d4b77040> in <module>
----> 1 ds_lat_lon.dims.index

AttributeError: 'Frozen' object has no attribute 'index'```

Is this due to it being a dataset rather than data array?

**Comment by jbusecke** [comment]
Can you update to the newest patch release `0.3.1`, and see if the problem persists? I believe this was fixed in #83.

**Comment by scollis** [comment]
Awesome will do  From: Julius Busecke ***@***.***>Date: Wednesday, March 23, 2022 at 3:17 PMTo: jbusecke/xmovie ***@***.***>Cc: Scott ***@***.***>, Author ***@***.***>Subject: Re: [jbusecke/xmovie] Error saving when using parallel option on Dataset, index error on the dims (Issue #88)Can you update to the newest patch release 0.3.1, and see if the problem persists? I believe this was fixed in #83.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by scollis** [comment]
Wow.. don't know what that was but all good

**Comment by jbusecke** [comment]
Awesome!  Glad it worked out.
